# Generated by Django 3.1.7 on 2021-02-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mailid', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('numavail', models.IntegerField(default=1)),
                ('societyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.society')),
            ],
        ),
    ]
