# Generated by Django 3.1.7 on 2021-03-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='societyname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.societyadmin'),
        ),
        migrations.DeleteModel(
            name='Society',
        ),
    ]
